splash = false
ipc = true
wallpaper {
  monitor = eDP-1
  path = ~/.config/backgrounds/001.webp
  fit_mode = cover
}
wallpaper {
  monitor = DP-3
  path = ~/.config/backgrounds/002.webp
  fit_mode = cover
}
